"""Configuration loader for Snippy.

Loads `config.json` from the OS-appropriate user data directory
(see `platformdirs.user_config_dir`). On first launch, writes a default
config file so the user has something to look at.

Phase 1 schema (will grow over time):

    {
        "hotkey": "Ctrl+Space",
        "theme": "midnight",
        "capture": {
            "enabled": true,
            "blacklist_regex": ["..."],
            "max_snippet_length": 50000,
            "max_snippets": 50000
        },
        "ui": {
            "palette_width": 640,
            "show_type_icons": true,
            "sound_on_capture": false
        },
        "feedback": {
            "toast": true,
            "tray_flash": true,
            "palette_pulse": true,
            "sound": false,
            "os_notification": false,
            "sensitive_warning": true
        },
        "sync": {
            "api_port": 8732,
            "api_token": "<auto-generated>"
        }
    }
"""
from __future__ import annotations

import json
import logging
import secrets
import sys
from dataclasses import asdict, dataclass, field, replace
from pathlib import Path
from typing import Any

from platformdirs import user_config_dir

from snippy import __app_name__


LOGGER = logging.getLogger(__name__)

CONFIG_FILENAME = "config.json"


# ---------------------------------------------------------------------------
# Typed config sections
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class CaptureConfig:
    enabled: bool = True
    blacklist_regex: list[str] = field(
        default_factory=lambda: [
            r"(?i)password\s*[:=]\s*\S+",
            r"(?i)api[_-]?key\s*[:=]\s*\S+",
        ]
    )
    max_snippet_length: int = 50_000
    max_snippets: int = 50_000
    # Image capture settings
    # On macOS, avoid Ctrl+Space (input-source switcher) and keep the image
    # hotkey distinct from the history hotkey. Command+Shift+Space is free.
    image_hotkey: str = field(
        default_factory=lambda: "Ctrl+Shift+Command+Space" if sys.platform == "darwin" else "Ctrl+Shift+Space"
    )
    image_save_dir: str | None = None  # None -> user's Pictures folder
    image_copy_to_clipboard: bool = True


@dataclass(slots=True)
class UiConfig:
    palette_width: int = 640
    show_type_icons: bool = True


@dataclass(slots=True)
class FeedbackConfig:
    toast: bool = True
    tray_flash: bool = True
    palette_pulse: bool = True
    sound: bool = False
    os_notification: bool = False
    sensitive_warning: bool = True


@dataclass(slots=True)
class SyncConfig:
    api_port: int = 8732
    api_token: str = ""  # auto-generated on first run


@dataclass(slots=True)
class BackupConfig:
    """Phase 3a: backup scheduler config."""
    last_backup_at: str | None = None  # ISO 8601 UTC string; None = never
    reminder_days: int = 7  # how long before the user gets a reminder toast


@dataclass(slots=True)
class SnippyConfig:
    # Default hotkey is Ctrl+Space (Windows/Linux). On macOS we avoid
    # Ctrl+Space because it conflicts with the system input-source switcher.
    hotkey: str = field(default_factory=lambda: "Ctrl+Shift+Space" if sys.platform == "darwin" else "Ctrl+Space")
    theme: str = "midnight"
    capture: CaptureConfig = field(default_factory=CaptureConfig)
    ui: UiConfig = field(default_factory=UiConfig)
    feedback: FeedbackConfig = field(default_factory=FeedbackConfig)
    sync: SyncConfig = field(default_factory=SyncConfig)
    backup: BackupConfig = field(default_factory=BackupConfig)


# ---------------------------------------------------------------------------
# Default + load + save
# ---------------------------------------------------------------------------


def _config_dir() -> Path:
    """Return (and create) the platform-appropriate config directory."""
    path = Path(user_config_dir(__app_name__, appauthor=__app_name__))
    path.mkdir(parents=True, exist_ok=True)
    return path


def config_path() -> Path:
    """Return the path to config.json (does not guarantee it exists)."""
    return _config_dir() / CONFIG_FILENAME


def _default_config() -> SnippyConfig:
    cfg = SnippyConfig()
    cfg.sync.api_token = secrets.token_urlsafe(24)
    return cfg


def _merge_dict_into_dataclass(dc: Any, data: dict[str, Any]) -> None:
    """Recursively merge dict values into an existing dataclass instance in place."""
    for key, value in data.items():
        if not hasattr(dc, key):
            LOGGER.debug("Ignoring unknown config key: %r", key)
            continue
        current = getattr(dc, key)
        if isinstance(current, dataclass_type := type(current)) and isinstance(value, dict):
            # nested dataclass — recurse
            from dataclasses import is_dataclass

            if is_dataclass(current):
                _merge_dict_into_dataclass(current, value)
                continue
        setattr(dc, key, value)


# Avoid circular import issues by importing the name locally.
def dataclass_type(_t: Any) -> type:  # pragma: no cover — type helper only
    return type(_t)


def load_config(path: Path | None = None) -> SnippyConfig:
    """Load the config from disk, or return defaults + write a fresh file.

    The returned object is always a fully-populated `SnippyConfig` — missing
    keys are filled in with defaults. Unknown keys are silently ignored.
    """
    cfg_path = path or config_path()
    if not cfg_path.exists():
        cfg = _default_config()
        save_config(cfg, cfg_path)
        LOGGER.info("Created default config at %s", cfg_path)
        return cfg

    try:
        raw = json.loads(cfg_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        LOGGER.warning("Failed to read config at %s: %s. Using defaults.", cfg_path, exc)
        return _default_config()

    cfg = _default_config()
    if isinstance(raw, dict):
        _merge_dict_into_dataclass(cfg, raw)
    else:
        LOGGER.warning("Config root is not a dict; using defaults.")
    return cfg


def save_config(cfg: SnippyConfig, path: Path | None = None) -> None:
    """Write the config to disk as pretty-printed JSON."""
    cfg_path = path or config_path()
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    cfg_path.write_text(
        json.dumps(asdict(cfg), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    LOGGER.debug("Wrote config to %s", cfg_path)


def update_config(cfg: SnippyConfig, **changes: Any) -> SnippyConfig:
    """Return a new config with the given top-level changes applied."""
    return replace(cfg, **changes)